// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATCOMmDwq6ohhVIi1yycndrVFVmQ73WgU',
    appId: '1:895811068766:web:6988f89d3a2858248165cf',
    messagingSenderId: '895811068766',
    projectId: 'write-out-f2782',
    authDomain: 'write-out-f2782.firebaseapp.com',
    databaseURL: 'https://write-out-f2782-default-rtdb.firebaseio.com',
    storageBucket: 'write-out-f2782.appspot.com',
    measurementId: 'G-GF0XWXG92L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYeP4yBnnX_CliQoJzrbeo9_WxsRaIfUg',
    appId: '1:895811068766:android:5786b63c1534c33b8165cf',
    messagingSenderId: '895811068766',
    projectId: 'write-out-f2782',
    databaseURL: 'https://write-out-f2782-default-rtdb.firebaseio.com',
    storageBucket: 'write-out-f2782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXT9ufJxIbNUHw8sio63gn4AlPhEKdP3Y',
    appId: '1:895811068766:ios:ec964f8a96d68c408165cf',
    messagingSenderId: '895811068766',
    projectId: 'write-out-f2782',
    databaseURL: 'https://write-out-f2782-default-rtdb.firebaseio.com',
    storageBucket: 'write-out-f2782.appspot.com',
    iosClientId: '895811068766-oqr53jbo5iq1lpf1lul2t3ttbelb44ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.writeoutWebAndroidIos',
  );
}
